/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model.impl;

import com.dkcb.model.Bacsi;

import com.dkcb.service.BacsiLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Bacsi service. Represents a row in the &quot;u_Bacsi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BacsiImpl}.
 * </p>
 *
 * @author hoang_000
 * @see BacsiImpl
 * @see com.dkcb.model.Bacsi
 * @generated
 */
public abstract class BacsiBaseImpl extends BacsiModelImpl implements Bacsi {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bacsi model instance should use the {@link Bacsi} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BacsiLocalServiceUtil.addBacsi(this);
		}
		else {
			BacsiLocalServiceUtil.updateBacsi(this);
		}
	}
}