/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model.impl;

import com.dkcb.model.Dichvu;

import com.dkcb.service.DichvuLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Dichvu service. Represents a row in the &quot;u_Dichvu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DichvuImpl}.
 * </p>
 *
 * @author hoang_000
 * @see DichvuImpl
 * @see com.dkcb.model.Dichvu
 * @generated
 */
public abstract class DichvuBaseImpl extends DichvuModelImpl implements Dichvu {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dichvu model instance should use the {@link Dichvu} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			DichvuLocalServiceUtil.addDichvu(this);
		}
		else {
			DichvuLocalServiceUtil.updateDichvu(this);
		}
	}
}