/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model.impl;

import com.dkcb.model.Lichkham;

import com.dkcb.service.LichkhamLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Lichkham service. Represents a row in the &quot;u_Lichkham&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LichkhamImpl}.
 * </p>
 *
 * @author hoang_000
 * @see LichkhamImpl
 * @see com.dkcb.model.Lichkham
 * @generated
 */
public abstract class LichkhamBaseImpl extends LichkhamModelImpl
	implements Lichkham {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lichkham model instance should use the {@link Lichkham} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LichkhamLocalServiceUtil.addLichkham(this);
		}
		else {
			LichkhamLocalServiceUtil.updateLichkham(this);
		}
	}
}