/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LoaiVB service. Represents a row in the &quot;vanban_LoaiVB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vanban.model.impl.LoaiVBModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vanban.model.impl.LoaiVBImpl}.
 * </p>
 *
 * @author nguye
 * @see LoaiVB
 * @see com.vanban.model.impl.LoaiVBImpl
 * @see com.vanban.model.impl.LoaiVBModelImpl
 * @generated
 */
public interface LoaiVBModel extends BaseModel<LoaiVB> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai v b model instance should use the {@link LoaiVB} interface instead.
	 */

	/**
	 * Returns the primary key of this loai v b.
	 *
	 * @return the primary key of this loai v b
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loai v b.
	 *
	 * @param primaryKey the primary key of this loai v b
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loai ID of this loai v b.
	 *
	 * @return the loai ID of this loai v b
	 */
	public long getLoaiId();

	/**
	 * Sets the loai ID of this loai v b.
	 *
	 * @param loaiId the loai ID of this loai v b
	 */
	public void setLoaiId(long loaiId);

	/**
	 * Returns the tenloai of this loai v b.
	 *
	 * @return the tenloai of this loai v b
	 */
	@AutoEscape
	public String getTenloai();

	/**
	 * Sets the tenloai of this loai v b.
	 *
	 * @param tenloai the tenloai of this loai v b
	 */
	public void setTenloai(String tenloai);

	/**
	 * Returns the ghichu of this loai v b.
	 *
	 * @return the ghichu of this loai v b
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this loai v b.
	 *
	 * @param ghichu the ghichu of this loai v b
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the tinhtrang of this loai v b.
	 *
	 * @return the tinhtrang of this loai v b
	 */
	public boolean getTinhtrang();

	/**
	 * Returns <code>true</code> if this loai v b is tinhtrang.
	 *
	 * @return <code>true</code> if this loai v b is tinhtrang; <code>false</code> otherwise
	 */
	public boolean isTinhtrang();

	/**
	 * Sets whether this loai v b is tinhtrang.
	 *
	 * @param tinhtrang the tinhtrang of this loai v b
	 */
	public void setTinhtrang(boolean tinhtrang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vanban.model.LoaiVB loaiVB);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vanban.model.LoaiVB> toCacheModel();

	@Override
	public com.vanban.model.LoaiVB toEscapedModel();

	@Override
	public com.vanban.model.LoaiVB toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}