/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the nguoiki service. Represents a row in the &quot;vanban_nguoiki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vanban.model.impl.nguoikiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vanban.model.impl.nguoikiImpl}.
 * </p>
 *
 * @author nguye
 * @see nguoiki
 * @see com.vanban.model.impl.nguoikiImpl
 * @see com.vanban.model.impl.nguoikiModelImpl
 * @generated
 */
public interface nguoikiModel extends BaseModel<nguoiki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nguoiki model instance should use the {@link nguoiki} interface instead.
	 */

	/**
	 * Returns the primary key of this nguoiki.
	 *
	 * @return the primary key of this nguoiki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nguoiki.
	 *
	 * @param primaryKey the primary key of this nguoiki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the nguoiki i d of this nguoiki.
	 *
	 * @return the nguoiki i d of this nguoiki
	 */
	public long getNguoikiID();

	/**
	 * Sets the nguoiki i d of this nguoiki.
	 *
	 * @param nguoikiID the nguoiki i d of this nguoiki
	 */
	public void setNguoikiID(long nguoikiID);

	/**
	 * Returns the hoten of this nguoiki.
	 *
	 * @return the hoten of this nguoiki
	 */
	@AutoEscape
	public String getHoten();

	/**
	 * Sets the hoten of this nguoiki.
	 *
	 * @param hoten the hoten of this nguoiki
	 */
	public void setHoten(String hoten);

	/**
	 * Returns the ngaysinh of this nguoiki.
	 *
	 * @return the ngaysinh of this nguoiki
	 */
	public Date getNgaysinh();

	/**
	 * Sets the ngaysinh of this nguoiki.
	 *
	 * @param ngaysinh the ngaysinh of this nguoiki
	 */
	public void setNgaysinh(Date ngaysinh);

	/**
	 * Returns the gioitinh of this nguoiki.
	 *
	 * @return the gioitinh of this nguoiki
	 */
	public int getGioitinh();

	/**
	 * Sets the gioitinh of this nguoiki.
	 *
	 * @param gioitinh the gioitinh of this nguoiki
	 */
	public void setGioitinh(int gioitinh);

	/**
	 * Returns the donvi of this nguoiki.
	 *
	 * @return the donvi of this nguoiki
	 */
	@AutoEscape
	public String getDonvi();

	/**
	 * Sets the donvi of this nguoiki.
	 *
	 * @param donvi the donvi of this nguoiki
	 */
	public void setDonvi(String donvi);

	/**
	 * Returns the chucvu of this nguoiki.
	 *
	 * @return the chucvu of this nguoiki
	 */
	@AutoEscape
	public String getChucvu();

	/**
	 * Sets the chucvu of this nguoiki.
	 *
	 * @param chucvu the chucvu of this nguoiki
	 */
	public void setChucvu(String chucvu);

	/**
	 * Returns the tinhtrang of this nguoiki.
	 *
	 * @return the tinhtrang of this nguoiki
	 */
	public boolean getTinhtrang();

	/**
	 * Returns <code>true</code> if this nguoiki is tinhtrang.
	 *
	 * @return <code>true</code> if this nguoiki is tinhtrang; <code>false</code> otherwise
	 */
	public boolean isTinhtrang();

	/**
	 * Sets whether this nguoiki is tinhtrang.
	 *
	 * @param tinhtrang the tinhtrang of this nguoiki
	 */
	public void setTinhtrang(boolean tinhtrang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vanban.model.nguoiki nguoiki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vanban.model.nguoiki> toCacheModel();

	@Override
	public com.vanban.model.nguoiki toEscapedModel();

	@Override
	public com.vanban.model.nguoiki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}