/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the noiBanHanh service. Represents a row in the &quot;vanban_noiBanHanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vanban.model.impl.noiBanHanhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vanban.model.impl.noiBanHanhImpl}.
 * </p>
 *
 * @author nguye
 * @see noiBanHanh
 * @see com.vanban.model.impl.noiBanHanhImpl
 * @see com.vanban.model.impl.noiBanHanhModelImpl
 * @generated
 */
public interface noiBanHanhModel extends BaseModel<noiBanHanh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a noi ban hanh model instance should use the {@link noiBanHanh} interface instead.
	 */

	/**
	 * Returns the primary key of this noi ban hanh.
	 *
	 * @return the primary key of this noi ban hanh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this noi ban hanh.
	 *
	 * @param primaryKey the primary key of this noi ban hanh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the noi b h ID of this noi ban hanh.
	 *
	 * @return the noi b h ID of this noi ban hanh
	 */
	public long getNoiBHId();

	/**
	 * Sets the noi b h ID of this noi ban hanh.
	 *
	 * @param noiBHId the noi b h ID of this noi ban hanh
	 */
	public void setNoiBHId(long noiBHId);

	/**
	 * Returns the tennoibanhanh of this noi ban hanh.
	 *
	 * @return the tennoibanhanh of this noi ban hanh
	 */
	@AutoEscape
	public String getTennoibanhanh();

	/**
	 * Sets the tennoibanhanh of this noi ban hanh.
	 *
	 * @param tennoibanhanh the tennoibanhanh of this noi ban hanh
	 */
	public void setTennoibanhanh(String tennoibanhanh);

	/**
	 * Returns the ghichu of this noi ban hanh.
	 *
	 * @return the ghichu of this noi ban hanh
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this noi ban hanh.
	 *
	 * @param ghichu the ghichu of this noi ban hanh
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the tinhtrang of this noi ban hanh.
	 *
	 * @return the tinhtrang of this noi ban hanh
	 */
	public boolean getTinhtrang();

	/**
	 * Returns <code>true</code> if this noi ban hanh is tinhtrang.
	 *
	 * @return <code>true</code> if this noi ban hanh is tinhtrang; <code>false</code> otherwise
	 */
	public boolean isTinhtrang();

	/**
	 * Sets whether this noi ban hanh is tinhtrang.
	 *
	 * @param tinhtrang the tinhtrang of this noi ban hanh
	 */
	public void setTinhtrang(boolean tinhtrang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vanban.model.noiBanHanh noiBanHanh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vanban.model.noiBanHanh> toCacheModel();

	@Override
	public com.vanban.model.noiBanHanh toEscapedModel();

	@Override
	public com.vanban.model.noiBanHanh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}