/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the user service. Represents a row in the &quot;vanban_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vanban.model.impl.userModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vanban.model.impl.userImpl}.
 * </p>
 *
 * @author nguye
 * @see user
 * @see com.vanban.model.impl.userImpl
 * @see com.vanban.model.impl.userModelImpl
 * @generated
 */
public interface userModel extends BaseModel<user> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user model instance should use the {@link user} interface instead.
	 */

	/**
	 * Returns the primary key of this user.
	 *
	 * @return the primary key of this user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user.
	 *
	 * @param primaryKey the primary key of this user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user.
	 *
	 * @return the user ID of this user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user.
	 *
	 * @param userId the user ID of this user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user.
	 *
	 * @return the user uuid of this user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user.
	 *
	 * @param userUuid the user uuid of this user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the hoten of this user.
	 *
	 * @return the hoten of this user
	 */
	@AutoEscape
	public String getHoten();

	/**
	 * Sets the hoten of this user.
	 *
	 * @param hoten the hoten of this user
	 */
	public void setHoten(String hoten);

	/**
	 * Returns the ngaysinh of this user.
	 *
	 * @return the ngaysinh of this user
	 */
	public Date getNgaysinh();

	/**
	 * Sets the ngaysinh of this user.
	 *
	 * @param ngaysinh the ngaysinh of this user
	 */
	public void setNgaysinh(Date ngaysinh);

	/**
	 * Returns the gioitinh of this user.
	 *
	 * @return the gioitinh of this user
	 */
	public int getGioitinh();

	/**
	 * Sets the gioitinh of this user.
	 *
	 * @param gioitinh the gioitinh of this user
	 */
	public void setGioitinh(int gioitinh);

	/**
	 * Returns the diachi of this user.
	 *
	 * @return the diachi of this user
	 */
	@AutoEscape
	public String getDiachi();

	/**
	 * Sets the diachi of this user.
	 *
	 * @param diachi the diachi of this user
	 */
	public void setDiachi(String diachi);

	/**
	 * Returns the sdt of this user.
	 *
	 * @return the sdt of this user
	 */
	@AutoEscape
	public String getSdt();

	/**
	 * Sets the sdt of this user.
	 *
	 * @param sdt the sdt of this user
	 */
	public void setSdt(String sdt);

	/**
	 * Returns the donvi of this user.
	 *
	 * @return the donvi of this user
	 */
	@AutoEscape
	public String getDonvi();

	/**
	 * Sets the donvi of this user.
	 *
	 * @param donvi the donvi of this user
	 */
	public void setDonvi(String donvi);

	/**
	 * Returns the mail of this user.
	 *
	 * @return the mail of this user
	 */
	@AutoEscape
	public String getMail();

	/**
	 * Sets the mail of this user.
	 *
	 * @param mail the mail of this user
	 */
	public void setMail(String mail);

	/**
	 * Returns the matkhau of this user.
	 *
	 * @return the matkhau of this user
	 */
	@AutoEscape
	public String getMatkhau();

	/**
	 * Sets the matkhau of this user.
	 *
	 * @param matkhau the matkhau of this user
	 */
	public void setMatkhau(String matkhau);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vanban.model.user user);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vanban.model.user> toCacheModel();

	@Override
	public com.vanban.model.user toEscapedModel();

	@Override
	public com.vanban.model.user toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}