/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the vanban service. Represents a row in the &quot;vanban_vanban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vanban.model.impl.vanbanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vanban.model.impl.vanbanImpl}.
 * </p>
 *
 * @author nguye
 * @see vanban
 * @see com.vanban.model.impl.vanbanImpl
 * @see com.vanban.model.impl.vanbanModelImpl
 * @generated
 */
public interface vanbanModel extends BaseModel<vanban> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vanban model instance should use the {@link vanban} interface instead.
	 */

	/**
	 * Returns the primary key of this vanban.
	 *
	 * @return the primary key of this vanban
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vanban.
	 *
	 * @param primaryKey the primary key of this vanban
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vanban ID of this vanban.
	 *
	 * @return the vanban ID of this vanban
	 */
	public long getVanbanId();

	/**
	 * Sets the vanban ID of this vanban.
	 *
	 * @param vanbanId the vanban ID of this vanban
	 */
	public void setVanbanId(long vanbanId);

	/**
	 * Returns the kihieu of this vanban.
	 *
	 * @return the kihieu of this vanban
	 */
	@AutoEscape
	public String getKihieu();

	/**
	 * Sets the kihieu of this vanban.
	 *
	 * @param kihieu the kihieu of this vanban
	 */
	public void setKihieu(String kihieu);

	/**
	 * Returns the trichyeu of this vanban.
	 *
	 * @return the trichyeu of this vanban
	 */
	@AutoEscape
	public String getTrichyeu();

	/**
	 * Sets the trichyeu of this vanban.
	 *
	 * @param trichyeu the trichyeu of this vanban
	 */
	public void setTrichyeu(String trichyeu);

	/**
	 * Returns the ngaybanhanh of this vanban.
	 *
	 * @return the ngaybanhanh of this vanban
	 */
	public Date getNgaybanhanh();

	/**
	 * Sets the ngaybanhanh of this vanban.
	 *
	 * @param ngaybanhanh the ngaybanhanh of this vanban
	 */
	public void setNgaybanhanh(Date ngaybanhanh);

	/**
	 * Returns the ngaytao of this vanban.
	 *
	 * @return the ngaytao of this vanban
	 */
	public Date getNgaytao();

	/**
	 * Sets the ngaytao of this vanban.
	 *
	 * @param ngaytao the ngaytao of this vanban
	 */
	public void setNgaytao(Date ngaytao);

	/**
	 * Returns the nguoiki i d of this vanban.
	 *
	 * @return the nguoiki i d of this vanban
	 */
	public long getNguoikiID();

	/**
	 * Sets the nguoiki i d of this vanban.
	 *
	 * @param nguoikiID the nguoiki i d of this vanban
	 */
	public void setNguoikiID(long nguoikiID);

	/**
	 * Returns the user i d of this vanban.
	 *
	 * @return the user i d of this vanban
	 */
	public long getUserID();

	/**
	 * Sets the user i d of this vanban.
	 *
	 * @param userID the user i d of this vanban
	 */
	public void setUserID(long userID);

	/**
	 * Returns the loai i d of this vanban.
	 *
	 * @return the loai i d of this vanban
	 */
	public long getLoaiID();

	/**
	 * Sets the loai i d of this vanban.
	 *
	 * @param loaiID the loai i d of this vanban
	 */
	public void setLoaiID(long loaiID);

	/**
	 * Returns the noi b h i d of this vanban.
	 *
	 * @return the noi b h i d of this vanban
	 */
	public long getNoiBHID();

	/**
	 * Sets the noi b h i d of this vanban.
	 *
	 * @param noiBHID the noi b h i d of this vanban
	 */
	public void setNoiBHID(long noiBHID);

	/**
	 * Returns the tinhtrang of this vanban.
	 *
	 * @return the tinhtrang of this vanban
	 */
	public boolean getTinhtrang();

	/**
	 * Returns <code>true</code> if this vanban is tinhtrang.
	 *
	 * @return <code>true</code> if this vanban is tinhtrang; <code>false</code> otherwise
	 */
	public boolean isTinhtrang();

	/**
	 * Sets whether this vanban is tinhtrang.
	 *
	 * @param tinhtrang the tinhtrang of this vanban
	 */
	public void setTinhtrang(boolean tinhtrang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vanban.model.vanban vanban);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vanban.model.vanban> toCacheModel();

	@Override
	public com.vanban.model.vanban toEscapedModel();

	@Override
	public com.vanban.model.vanban toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}