/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Dichvu service. Represents a row in the &quot;u_Dichvu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dkcb.model.impl.DichvuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dkcb.model.impl.DichvuImpl}.
 * </p>
 *
 * @author hoang_000
 * @see Dichvu
 * @see com.dkcb.model.impl.DichvuImpl
 * @see com.dkcb.model.impl.DichvuModelImpl
 * @generated
 */
public interface DichvuModel extends BaseModel<Dichvu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dichvu model instance should use the {@link Dichvu} interface instead.
	 */

	/**
	 * Returns the primary key of this dichvu.
	 *
	 * @return the primary key of this dichvu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dichvu.
	 *
	 * @param primaryKey the primary key of this dichvu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the iddichvu of this dichvu.
	 *
	 * @return the iddichvu of this dichvu
	 */
	public long getIddichvu();

	/**
	 * Sets the iddichvu of this dichvu.
	 *
	 * @param Iddichvu the iddichvu of this dichvu
	 */
	public void setIddichvu(long Iddichvu);

	/**
	 * Returns the tendichvu of this dichvu.
	 *
	 * @return the tendichvu of this dichvu
	 */
	@AutoEscape
	public String getTendichvu();

	/**
	 * Sets the tendichvu of this dichvu.
	 *
	 * @param Tendichvu the tendichvu of this dichvu
	 */
	public void setTendichvu(String Tendichvu);

	/**
	 * Returns the mucthu of this dichvu.
	 *
	 * @return the mucthu of this dichvu
	 */
	public double getMucthu();

	/**
	 * Sets the mucthu of this dichvu.
	 *
	 * @param Mucthu the mucthu of this dichvu
	 */
	public void setMucthu(double Mucthu);

	/**
	 * Returns the ghichi of this dichvu.
	 *
	 * @return the ghichi of this dichvu
	 */
	@AutoEscape
	public String getGhichi();

	/**
	 * Sets the ghichi of this dichvu.
	 *
	 * @param Ghichi the ghichi of this dichvu
	 */
	public void setGhichi(String Ghichi);

	/**
	 * Returns the idphongkham of this dichvu.
	 *
	 * @return the idphongkham of this dichvu
	 */
	@AutoEscape
	public String getIdphongkham();

	/**
	 * Sets the idphongkham of this dichvu.
	 *
	 * @param Idphongkham the idphongkham of this dichvu
	 */
	public void setIdphongkham(String Idphongkham);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.dkcb.model.Dichvu dichvu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.dkcb.model.Dichvu> toCacheModel();

	@Override
	public com.dkcb.model.Dichvu toEscapedModel();

	@Override
	public com.dkcb.model.Dichvu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}