/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DKCB service. Represents a row in the &quot;u_DKCB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dkcb.model.impl.DKCBModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dkcb.model.impl.DKCBImpl}.
 * </p>
 *
 * @author hoang_000
 * @see DKCB
 * @see com.dkcb.model.impl.DKCBImpl
 * @see com.dkcb.model.impl.DKCBModelImpl
 * @generated
 */
public interface DKCBModel extends BaseModel<DKCB> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d k c b model instance should use the {@link DKCB} interface instead.
	 */

	/**
	 * Returns the primary key of this d k c b.
	 *
	 * @return the primary key of this d k c b
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d k c b.
	 *
	 * @param primaryKey the primary key of this d k c b
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this d k c b.
	 *
	 * @return the ID of this d k c b
	 */
	public long getId();

	/**
	 * Sets the ID of this d k c b.
	 *
	 * @param Id the ID of this d k c b
	 */
	public void setId(long Id);

	/**
	 * Returns the hoten of this d k c b.
	 *
	 * @return the hoten of this d k c b
	 */
	@AutoEscape
	public String getHoten();

	/**
	 * Sets the hoten of this d k c b.
	 *
	 * @param Hoten the hoten of this d k c b
	 */
	public void setHoten(String Hoten);

	/**
	 * Returns the diachi of this d k c b.
	 *
	 * @return the diachi of this d k c b
	 */
	@AutoEscape
	public String getDiachi();

	/**
	 * Sets the diachi of this d k c b.
	 *
	 * @param Diachi the diachi of this d k c b
	 */
	public void setDiachi(String Diachi);

	/**
	 * Returns the gioitinh of this d k c b.
	 *
	 * @return the gioitinh of this d k c b
	 */
	public boolean getGioitinh();

	/**
	 * Returns <code>true</code> if this d k c b is gioitinh.
	 *
	 * @return <code>true</code> if this d k c b is gioitinh; <code>false</code> otherwise
	 */
	public boolean isGioitinh();

	/**
	 * Sets whether this d k c b is gioitinh.
	 *
	 * @param Gioitinh the gioitinh of this d k c b
	 */
	public void setGioitinh(boolean Gioitinh);

	/**
	 * Returns the sodienthoai of this d k c b.
	 *
	 * @return the sodienthoai of this d k c b
	 */
	@AutoEscape
	public String getSodienthoai();

	/**
	 * Sets the sodienthoai of this d k c b.
	 *
	 * @param Sodienthoai the sodienthoai of this d k c b
	 */
	public void setSodienthoai(String Sodienthoai);

	/**
	 * Returns the ngaysinh of this d k c b.
	 *
	 * @return the ngaysinh of this d k c b
	 */
	public Date getNgaysinh();

	/**
	 * Sets the ngaysinh of this d k c b.
	 *
	 * @param Ngaysinh the ngaysinh of this d k c b
	 */
	public void setNgaysinh(Date Ngaysinh);

	/**
	 * Returns the trieuchung of this d k c b.
	 *
	 * @return the trieuchung of this d k c b
	 */
	@AutoEscape
	public String getTrieuchung();

	/**
	 * Sets the trieuchung of this d k c b.
	 *
	 * @param Trieuchung the trieuchung of this d k c b
	 */
	public void setTrieuchung(String Trieuchung);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.dkcb.model.DKCB dkcb);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.dkcb.model.DKCB> toCacheModel();

	@Override
	public com.dkcb.model.DKCB toEscapedModel();

	@Override
	public com.dkcb.model.DKCB toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}