/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dkcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Lichkham service. Represents a row in the &quot;u_Lichkham&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dkcb.model.impl.LichkhamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dkcb.model.impl.LichkhamImpl}.
 * </p>
 *
 * @author hoang_000
 * @see Lichkham
 * @see com.dkcb.model.impl.LichkhamImpl
 * @see com.dkcb.model.impl.LichkhamModelImpl
 * @generated
 */
public interface LichkhamModel extends BaseModel<Lichkham> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lichkham model instance should use the {@link Lichkham} interface instead.
	 */

	/**
	 * Returns the primary key of this lichkham.
	 *
	 * @return the primary key of this lichkham
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this lichkham.
	 *
	 * @param primaryKey the primary key of this lichkham
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the idbacsi of this lichkham.
	 *
	 * @return the idbacsi of this lichkham
	 */
	@AutoEscape
	public String getIdbacsi();

	/**
	 * Sets the idbacsi of this lichkham.
	 *
	 * @param Idbacsi the idbacsi of this lichkham
	 */
	public void setIdbacsi(String Idbacsi);

	/**
	 * Returns the ID of this lichkham.
	 *
	 * @return the ID of this lichkham
	 */
	public long getId();

	/**
	 * Sets the ID of this lichkham.
	 *
	 * @param Id the ID of this lichkham
	 */
	public void setId(long Id);

	/**
	 * Returns the idphongkham of this lichkham.
	 *
	 * @return the idphongkham of this lichkham
	 */
	@AutoEscape
	public String getIdphongkham();

	/**
	 * Sets the idphongkham of this lichkham.
	 *
	 * @param Idphongkham the idphongkham of this lichkham
	 */
	public void setIdphongkham(String Idphongkham);

	/**
	 * Returns the iddichvu of this lichkham.
	 *
	 * @return the iddichvu of this lichkham
	 */
	public long getIddichvu();

	/**
	 * Sets the iddichvu of this lichkham.
	 *
	 * @param Iddichvu the iddichvu of this lichkham
	 */
	public void setIddichvu(long Iddichvu);

	/**
	 * Returns the giodukien of this lichkham.
	 *
	 * @return the giodukien of this lichkham
	 */
	@AutoEscape
	public String getGiodukien();

	/**
	 * Sets the giodukien of this lichkham.
	 *
	 * @param Giodukien the giodukien of this lichkham
	 */
	public void setGiodukien(String Giodukien);

	/**
	 * Returns the ngaykham of this lichkham.
	 *
	 * @return the ngaykham of this lichkham
	 */
	public Date getNgaykham();

	/**
	 * Sets the ngaykham of this lichkham.
	 *
	 * @param Ngaykham the ngaykham of this lichkham
	 */
	public void setNgaykham(Date Ngaykham);

	/**
	 * Returns the idlichkham of this lichkham.
	 *
	 * @return the idlichkham of this lichkham
	 */
	public int getIdlichkham();

	/**
	 * Sets the idlichkham of this lichkham.
	 *
	 * @param Idlichkham the idlichkham of this lichkham
	 */
	public void setIdlichkham(int Idlichkham);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.dkcb.model.Lichkham lichkham);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.dkcb.model.Lichkham> toCacheModel();

	@Override
	public com.dkcb.model.Lichkham toEscapedModel();

	@Override
	public com.dkcb.model.Lichkham toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}