/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vanban.model.LoaiVB;
import com.vanban.model.LoaiVBModel;
import com.vanban.model.LoaiVBSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LoaiVB service. Represents a row in the &quot;vanban_LoaiVB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vanban.model.LoaiVBModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiVBImpl}.
 * </p>
 *
 * @author nguye
 * @see LoaiVBImpl
 * @see com.vanban.model.LoaiVB
 * @see com.vanban.model.LoaiVBModel
 * @generated
 */
@JSON(strict = true)
public class LoaiVBModelImpl extends BaseModelImpl<LoaiVB>
	implements LoaiVBModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai v b model instance should use the {@link com.vanban.model.LoaiVB} interface instead.
	 */
	public static final String TABLE_NAME = "vanban_LoaiVB";
	public static final Object[][] TABLE_COLUMNS = {
			{ "loaiId", Types.BIGINT },
			{ "tenloai", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR },
			{ "tinhtrang", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table vanban_LoaiVB (loaiId LONG not null primary key,tenloai VARCHAR(75) null,ghichu VARCHAR(75) null,tinhtrang BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table vanban_LoaiVB";
	public static final String ORDER_BY_JPQL = " ORDER BY loaiVB.loaiId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vanban_LoaiVB.loaiId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vanban.model.LoaiVB"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vanban.model.LoaiVB"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LoaiVB toModel(LoaiVBSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LoaiVB model = new LoaiVBImpl();

		model.setLoaiId(soapModel.getLoaiId());
		model.setTenloai(soapModel.getTenloai());
		model.setGhichu(soapModel.getGhichu());
		model.setTinhtrang(soapModel.getTinhtrang());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LoaiVB> toModels(LoaiVBSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LoaiVB> models = new ArrayList<LoaiVB>(soapModels.length);

		for (LoaiVBSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vanban.model.LoaiVB"));

	public LoaiVBModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loaiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoaiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loaiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoaiVB.class;
	}

	@Override
	public String getModelClassName() {
		return LoaiVB.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("loaiId", getLoaiId());
		attributes.put("tenloai", getTenloai());
		attributes.put("ghichu", getGhichu());
		attributes.put("tinhtrang", getTinhtrang());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long loaiId = (Long)attributes.get("loaiId");

		if (loaiId != null) {
			setLoaiId(loaiId);
		}

		String tenloai = (String)attributes.get("tenloai");

		if (tenloai != null) {
			setTenloai(tenloai);
		}

		String ghichu = (String)attributes.get("ghichu");

		if (ghichu != null) {
			setGhichu(ghichu);
		}

		Boolean tinhtrang = (Boolean)attributes.get("tinhtrang");

		if (tinhtrang != null) {
			setTinhtrang(tinhtrang);
		}
	}

	@JSON
	@Override
	public long getLoaiId() {
		return _loaiId;
	}

	@Override
	public void setLoaiId(long loaiId) {
		_loaiId = loaiId;
	}

	@JSON
	@Override
	public String getTenloai() {
		if (_tenloai == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenloai;
		}
	}

	@Override
	public void setTenloai(String tenloai) {
		_tenloai = tenloai;
	}

	@JSON
	@Override
	public String getGhichu() {
		if (_ghichu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghichu;
		}
	}

	@Override
	public void setGhichu(String ghichu) {
		_ghichu = ghichu;
	}

	@JSON
	@Override
	public boolean getTinhtrang() {
		return _tinhtrang;
	}

	@Override
	public boolean isTinhtrang() {
		return _tinhtrang;
	}

	@Override
	public void setTinhtrang(boolean tinhtrang) {
		_tinhtrang = tinhtrang;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LoaiVB.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoaiVB toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoaiVB)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoaiVBImpl loaiVBImpl = new LoaiVBImpl();

		loaiVBImpl.setLoaiId(getLoaiId());
		loaiVBImpl.setTenloai(getTenloai());
		loaiVBImpl.setGhichu(getGhichu());
		loaiVBImpl.setTinhtrang(getTinhtrang());

		loaiVBImpl.resetOriginalValues();

		return loaiVBImpl;
	}

	@Override
	public int compareTo(LoaiVB loaiVB) {
		long primaryKey = loaiVB.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoaiVB)) {
			return false;
		}

		LoaiVB loaiVB = (LoaiVB)obj;

		long primaryKey = loaiVB.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LoaiVB> toCacheModel() {
		LoaiVBCacheModel loaiVBCacheModel = new LoaiVBCacheModel();

		loaiVBCacheModel.loaiId = getLoaiId();

		loaiVBCacheModel.tenloai = getTenloai();

		String tenloai = loaiVBCacheModel.tenloai;

		if ((tenloai != null) && (tenloai.length() == 0)) {
			loaiVBCacheModel.tenloai = null;
		}

		loaiVBCacheModel.ghichu = getGhichu();

		String ghichu = loaiVBCacheModel.ghichu;

		if ((ghichu != null) && (ghichu.length() == 0)) {
			loaiVBCacheModel.ghichu = null;
		}

		loaiVBCacheModel.tinhtrang = getTinhtrang();

		return loaiVBCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{loaiId=");
		sb.append(getLoaiId());
		sb.append(", tenloai=");
		sb.append(getTenloai());
		sb.append(", ghichu=");
		sb.append(getGhichu());
		sb.append(", tinhtrang=");
		sb.append(getTinhtrang());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.vanban.model.LoaiVB");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>loaiId</column-name><column-value><![CDATA[");
		sb.append(getLoaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenloai</column-name><column-value><![CDATA[");
		sb.append(getTenloai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghichu</column-name><column-value><![CDATA[");
		sb.append(getGhichu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tinhtrang</column-name><column-value><![CDATA[");
		sb.append(getTinhtrang());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LoaiVB.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { LoaiVB.class };
	private long _loaiId;
	private String _tenloai;
	private String _ghichu;
	private boolean _tinhtrang;
	private LoaiVB _escapedModel;
}