/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vanban.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.vanban.model.LoaiVB;

import com.vanban.service.LoaiVBLocalServiceUtil;

/**
 * The extended model base implementation for the LoaiVB service. Represents a row in the &quot;vanban_LoaiVB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiVBImpl}.
 * </p>
 *
 * @author nguye
 * @see LoaiVBImpl
 * @see com.vanban.model.LoaiVB
 * @generated
 */
public abstract class LoaiVBBaseImpl extends LoaiVBModelImpl implements LoaiVB {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai v b model instance should use the {@link LoaiVB} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LoaiVBLocalServiceUtil.addLoaiVB(this);
		}
		else {
			LoaiVBLocalServiceUtil.updateLoaiVB(this);
		}
	}
}